openapi: 3.0.0
info:
  title: Endpoint Specification
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /:
    post:
      summary: Endpoint to receive and process JSON payload
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payload'
      responses:
        '200':
          description: Successful response with processed payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
components:
  schemas:
    Payload:
      type: object
      properties:
        designation:
          type: string
        routes:
          type: array
          items:
            $ref: '#/components/schemas/Route'
    Route:
      type: object
      properties:
        designation:
          type: string
        routes:
          type: array
          items:
            $ref: '#/components/schemas/Route'
    Response:
      type: object
      properties:
        service:
          type: string
        response:
          type: array
          items:
            $ref: '#/components/schemas/ServiceResponse'
    ServiceResponse:
      type: object
      properties:
        service:
          type: string
        response:
          type: array
          items:
            $ref: '#/components/schemas/ServiceResponse'
